CREATE TABLE DEPARTMENTS (
DEPARTMENT_ID INT PRIMARY KEY,
DEPARTMENT_NAME VARCHAR(50));

CREATE TABLE COURSES (
COURSE_ID INT PRIMARY KEY,
COURSE_NAME VARCHAR(50),
DEPARTMENT_ID INT,
FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID));

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES
(1, 'COMPUTER SCIENCE'),
(2, 'MECHANICAL ENGINEERING'),
(3, 'PHYSICS'),
(4, 'ELECTRICAL ENGINEERING'),
(5, 'MATHEMATICS');

INSERT INTO COURSES (COURSE_ID, COURSE_NAME, DEPARTMENT_ID) VALUES
(101, 'DATA STRUCTURES', 1),
(102, 'ALGORITHMS', 1),
(103, 'OPERATING SYSTEMS', 1),
(104, 'DATABASE SYSTEMS', 1),
(201, 'THERMODYNAMICS', 2),
(202, 'FLUID MECHANICS', 2),
(203, 'MACHINE DESIGN', 2),
(301, 'CLASSICAL MECHANICS', 3),
(401, 'CIRCUIT THEORY', 4),
(402, 'DIGITAL LOGIC DESIGN', 4),
(501, 'CALCULUS', 5),
(502, 'LINEAR ALGEBRA', 5);

SELECT D.DEPARTMENT_NAME
FROM DEPARTMENTS D
JOIN COURSES C 
    ON D.DEPARTMENT_ID = C.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME
HAVING COUNT(C.COURSE_ID) > 2;
