CREATE TABLE AUTHORS(
AUTH_ID INT PRIMARY KEY,
AUTH_NAME VARCHAR(50),
COUNTRY VARCHAR(100));

CREATE TABLE BOOKS(
BOOK_ID INT PRIMARY KEY,
BOOK_NAME VARCHAR(50),
AUTH_ID INT,
PUBLISH_YEAR INT);

ALTER TABLE BOOKS
ADD CONSTRAINT fk_books_authors
FOREIGN KEY (AUTH_ID) REFERENCES AUTHORS(AUTH_ID);

INSERT INTO AUTHORS (AUTH_ID,AUTH_NAME,COUNTRY) VALUES
(1,'Tushar','INDIA'),
(2,'Anirudh','UNITED KINGDOM'),
(3,'Sameep Das','UNITED STATES');

INSERT INTO BOOKS (BOOK_ID, BOOK_NAME, AUTH_ID, PUBLISH_YEAR) VALUES
(1001, 'The Silent Observer', 1, 2021),
(1002, 'Echoes of Tomorrow', 2, 2021),
(1003, 'Beneath the Stars', 1, 2021),
(1004, 'Whispers in the Wind', 1, 2021),
(1005, 'The Last Horizon', 3, 2021),
(1006, 'Journey to the Unknown', 3, 2021),
(1007, 'The Dark Path', 2, 2021);

SELECT B.BOOK_ID,B.BOOK_NAME,B.PUBLISH_YEAR,A.AUTH_NAME,A.COUNTRY FROM
AUTHORS A INNER JOIN BOOKS B ON
A.AUTH_ID = B.AUTH_ID;